project_id = "aqoxkvmszdpbxwdcnhda"

[functions.link-card]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.charge-contribution]
verify_jwt = true

[functions.process-scheduled-contributions]
verify_jwt = false

[functions.process-cycle-payout]
verify_jwt = false

[functions.initiate-transfer]
verify_jwt = false

[functions.verify-bank-account]
verify_jwt = false

[functions.totp-setup]
verify_jwt = false

[functions.totp-verify]
verify_jwt = false

[functions.check-2fa-status]
verify_jwt = false