project_id = "aqoxkvmszdpbxwdcnhda"

[functions.paystack-webhook]
verify_jwt = false

[functions.charge-contribution]
verify_jwt = true

[functions.process-scheduled-contributions]
verify_jwt = false
